CLASS zfb_aufg_ulmd_unterklasse_1 DEFINITION INHERITING FROM zfb_aufg_ulmd_2
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zfb_aufg_ulmd_unterklasse_1 IMPLEMENTATION.
ENDCLASS.
