CLASS zcl_mj_wasser DEFINITION
  PUBLIC
  INHERITING FROM zcl_mj_getraenk
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_mj_wasser IMPLEMENTATION.
ENDCLASS.
