CLASS zst_schulung_uebung_sensor DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zst_schulung_uebung_sensor IMPLEMENTATION.
ENDCLASS.
