CLASS zmb_busse DEFINITION INHERITING FROM ZMB_KRAFTFAHRZEUG
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zmb_busse IMPLEMENTATION.
ENDCLASS.
