CLASS zmb_zweirad DEFINITION INHERITING FROM ZMB_KRAFTFAHRZEUG
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zmb_zweirad IMPLEMENTATION.
ENDCLASS.
