CLASS zlv_bus_unterklasse DEFINITION
  PUBLIC
  INHERITING FROM zlv_kraftfahrzeug
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zlv_bus_unterklasse IMPLEMENTATION.
ENDCLASS.
