CLASS zuh_motorrad DEFINITION INHERITING FROM ZUH_Kraftfahrzeug
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zuh_motorrad IMPLEMENTATION.
ENDCLASS.
