CLASS ztw_zweirad DEFINITION INHERITING FROM ztw_kraftfahrzeug
  PUBLIC
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ztw_zweirad IMPLEMENTATION.
ENDCLASS.
