CLASS z_hum_zweirad DEFINITION INHERITING FROM z_hum_kraftfahrzeug
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS z_hum_zweirad IMPLEMENTATION.
ENDCLASS.
