CLASS zod_busse DEFINITION INHERITING FROM zod_kraftfahrzeug
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zod_busse IMPLEMENTATION.
ENDCLASS.
