CLASS zod_zweirad DEFINITION INHERITING FROM zod_kraftfahrzeug
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zod_zweirad IMPLEMENTATION.
ENDCLASS.
