CLASS zem_passagier DEFINITION INHERITING FROM ZEM_FLUGZEUG
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zem_passagier IMPLEMENTATION.
ENDCLASS.
