CLASS zfd_busse DEFINITION INHERITING FROM zfd_kraftfahrzeug
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zfd_busse IMPLEMENTATION.
ENDCLASS.
