CLASS zfd_zweirad DEFINITION INHERITING FROM zfd_kraftfahrzeug
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zfd_zweirad IMPLEMENTATION.
ENDCLASS.
