CLASS zem_class2_pruefung DEFINITION
  PUBLIC INHERITING FROM zem_class1_pruefung
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zem_class2_pruefung IMPLEMENTATION.
ENDCLASS.
